### ISSUE TITLE
ignore the current bookml folder

### ISSUE THREAD

**Issue by hayden-MB** [vlmantova/bookml-action#1]
Hi there, is there a way of ignoring the current bookml folder in the repo when using this action, and replacing it with the version associated with the latest version of bookml?

**Comment by xworld21** [comment]
That would be the confusingly named option `replace-bookml`
```
- name: Compile with BookML
  uses: vlmantova/bookml-action@v1
  with:
    replace-bookml: true
```
which means 'replace the bookml folder with whatever is baked in the Docker image', thus the latest one, unless you also specify `version`.
